namespace IranVsTuran.Localization
{
    public static partial class Strings
    {
        /// <summary>Menus, HUD, shop, battle pass and other interface text.</summary>
        static readonly string[][] UI =
        {
            new[] { "game.title", "IRAN vs TURAN", "ایران و توران" },
            new[] { "game.subtitle", "Legends of the Shahnameh", "افسانه‌های شاهنامه" },
            new[] { "ui.ok", "OK", "باشه" },
            new[] { "ui.cancel", "Cancel", "انصراف" },

            new[] { "menu.play", "Play", "نبرد" },
            new[] { "menu.heroes", "Heroes", "پهلوانان" },
            new[] { "menu.shop", "Shop", "بازار" },
            new[] { "menu.pass", "Battle Pass", "نبردنامه" },
            new[] { "menu.armory", "Armory", "زرادخانه" },
            new[] { "menu.book", "Foes", "دشمنان" },
            new[] { "menu.quit", "Quit", "خروج" },
            new[] { "menu.quit_title", "Leave the game?", "از بازی بیرون می‌روی؟" },
            new[] { "menu.quit_body", "Iran will wait for its champion.", "ایران چشم‌به‌راه پهلوانش می‌ماند." },

            new[] { "map.title", "Map of Iran and Turan", "نقشهٔ ایران و توران" },
            new[] { "map.iran", "IRAN", "ایران" },
            new[] { "map.turan", "TURAN", "توران" },
            new[] { "map.mazandaran", "Mazandaran", "مازندران" },
            new[] { "map.caspian", "Caspian Sea", "دریای کاسپین" },
            new[] { "map.locked", "Win the previous battle first.", "اول نبرد پیشین را ببر." },

            new[] { "level.enemies", "Enemies", "دشمنان" },
            new[] { "level.info", "{0} waves · {1} starting coins", "{0} موج · {1} سکهٔ آغازین" },
            new[] { "level.difficulty", "Difficulty", "دشواری" },
            new[] { "level.hero", "{0} · level {1}", "{0} · رده {1}" },
            new[] { "level.change_hero", "Change hero", "تغییر پهلوان" },
            new[] { "level.fight", "To battle!", "به نبرد!" },
            new[] { "difficulty.0", "Casual", "آسان" },
            new[] { "difficulty.1", "Normal", "معمولی" },
            new[] { "difficulty.2", "Veteran", "کهنه‌کار" },

            new[] { "heroes.title", "Heroes", "پهلوانان" },
            new[] { "heroes.level", "Level {0}/{1}", "رده {0}/{1}" },
            new[] { "heroes.stats", "Health {0} · Damage {1}", "جان {0} · آسیب {1}" },
            new[] { "heroes.select", "Choose", "برگزین" },
            new[] { "heroes.selected", "Chosen", "برگزیده" },
            new[] { "heroes.train", "Train {0}", "آموزش {0}" },
            new[] { "heroes.unlock_level", "Or win battle {0}", "یا نبرد {0} را ببر" },
            new[] { "heroes.buy_confirm", "Unlock {0} for {1} gems?", "{0} را با {1} گوهر به دست می‌آوری؟" },
            new[] { "heroes.skin_confirm", "Buy the {0} look for {1} gems?", "جامهٔ «{0}» را با {1} گوهر می‌خری؟" },
            new[] { "heroes.skin_pass", "{0}: a royal battle pass reward", "{0}: پاداش نبردنامهٔ شاهی" },

            new[] { "armory.title", "Armory", "زرادخانه" },
            new[] { "armory.max", "Mastered", "کامل" },

            new[] { "book.title", "Book of Foes", "نامهٔ دشمنان" },
            new[] { "book.hp", "Health: {0}", "جان: {0}" },
            new[] { "book.speed", "Speed: {0}", "تندی: {0}" },
            new[] { "book.fast", "fast", "تند" },
            new[] { "book.slow", "slow", "کُند" },
            new[] { "book.normal", "normal", "معمولی" },
            new[] { "book.armor", "Armour {0}% · Magic resist {1}%", "زره {0}٪ · پایداری در برابر جادو {1}٪" },
            new[] { "book.lives", "Lives taken: {0}", "جان‌های گرفته‌شده: {0}" },
            new[] { "book.flying", "Flies over soldiers", "از فراز سربازان پرواز می‌کند" },
            new[] { "book.ranged", "Attacks from range", "از دور حمله می‌کند" },

            new[] { "shop.title", "Bazaar", "بازار" },
            new[] { "shop.tab.offers", "Offers", "پیشنهادها" },
            new[] { "shop.tab.gems", "Gems", "گوهر" },
            new[] { "shop.tab.gold", "Gold", "زر" },
            new[] { "shop.tab.items", "Items", "ابزار" },
            new[] { "shop.tab.free", "Free", "رایگان" },
            new[] { "shop.badge.popular", "Popular", "پرطرفدار" },
            new[] { "shop.badge.best", "Best value", "بهترین" },
            new[] { "shop.badge.once", "One time", "یک‌بار" },
            new[] { "shop.owned", "Owned", "داری" },
            new[] { "shop.thanks", "Thank you! Your purchase has been delivered.", "سپاس! خریدت رسید." },
            new[] { "shop.have", "You have {0}", "داری: {0}" },
            new[] { "shop.watch", "Watch", "تماشا" },
            new[] { "shop.ads_left", "{0}/{1} left today", "امروز {0} از {1}" },
            new[] { "shop.not_enough_gems", "Not enough gems", "گوهر کافی نداری" },
            new[] { "shop.not_enough_gold", "Not enough gold", "زر کافی نداری" },
            new[] { "shop.pass_desc", "Unlock the royal track: Zal, two skins and many gems this season.", "مسیر شاهی را باز کن: زال، دو جامه و گوهرهای فراوان در این فصل." },
            new[] { "store.buy", "Buy", "خرید" },
            new[] { "store.test_title", "Test purchase", "خرید آزمایشی" },
            new[] { "store.test_body", "{0} ({1}). This is a test store: no money will be charged.", "{0} ({1}). این فروشگاه آزمایشی است و پولی برداشته نمی‌شود." },
            new[] { "ads.test", "TEST AD — the real ad network is not connected yet", "آگهی آزمایشی — شبکهٔ تبلیغات هنوز وصل نشده" },
            new[] { "ads.countdown", "Reward in {0}…", "پاداش تا {0} ثانیهٔ دیگر…" },
            new[] { "ads.reward_ready", "Reward earned! Close the ad.", "پاداش گرفتی! آگهی را ببند." },
            new[] { "ads.close", "Close", "بستن" },

            new[] { "reward.gold", "{0} gold", "{0} زر" },
            new[] { "reward.gems", "{0} gems", "{0} گوهر" },
            new[] { "reward.item", "{0} × {1}", "{0} × {1}" },
            new[] { "reward.xp", "{0} XP", "{0} امتیاز" },
            new[] { "reward.gold_word", "gold", "زر" },
            new[] { "reward.got", "+{1} {0}", "+{1} {0}" },

            new[] { "pass.title", "Battle Pass", "نبردنامه" },
            new[] { "pass.season", "Season {0}", "فصل {0}" },
            new[] { "pass.days_left", "{0} days left", "{0} روز مانده" },
            new[] { "pass.tier", "Tier {0}/{1}", "پله {0}/{1}" },
            new[] { "pass.free", "Free", "رایگان" },
            new[] { "pass.royal", "Royal", "شاهی" },
            new[] { "pass.buy", "Royal pass {0}", "نبردنامهٔ شاهی {0}" },
            new[] { "pass.royal_owned", "Royal pass active", "نبردنامهٔ شاهی فعال است" },
            new[] { "pass.skip", "+1 tier {0}", "+۱ پله {0}" },
            new[] { "pass.claim_all", "Claim all", "دریافت همه" },
            new[] { "pass.maxed", "All tiers reached", "همهٔ پله‌ها را رفتی" },
            new[] { "pass.need_royal", "Needs the royal pass", "نبردنامهٔ شاهی لازم است" },
            new[] { "pass.need_tier", "Reach tier {0} first", "اول به پلهٔ {0} برس" },

            new[] { "daily.title", "Daily gift", "هدیهٔ روزانه" },
            new[] { "daily.day", "Day {0}", "روز {0}" },
            new[] { "daily.claim", "Claim", "دریافت" },
            new[] { "daily.double", "Claim ×2", "دریافت دوبرابر" },
            new[] { "daily.come_back", "Come back tomorrow for the next gift.", "فردا برای هدیهٔ بعدی برگرد." },

            new[] { "settings.title", "Settings", "تنظیمات" },
            new[] { "settings.language", "Language", "زبان" },
            new[] { "settings.sound", "Sound", "صدا" },
            new[] { "settings.music", "Music", "موسیقی" },
            new[] { "settings.on", "On", "روشن" },
            new[] { "settings.off", "Off", "خاموش" },
            new[] { "settings.reset", "Reset progress", "پاک کردن پیشرفت" },
            new[] { "settings.reset_button", "Reset", "پاک کن" },
            new[] { "settings.reset_body", "All progress, gold, gems and heroes will be erased. Purchases cannot be restored this way.", "همهٔ پیشرفت، زر، گوهر و پهلوانان پاک می‌شوند." },
            new[] { "settings.credits", "Story after Ferdowsi's Shahnameh · Font: Vazirmatn", "داستان برگرفته از شاهنامهٔ فردوسی · قلم: وزیرمتن" },

            new[] { "story.skip", "Skip", "رد کردن" },
            new[] { "story.narrator", "Narrator", "راوی" },
            new[] { "story.tap", "Tap to continue", "برای ادامه لمس کن" },

            new[] { "battle.start", "Start!", "آغاز!" },
            new[] { "battle.next_in", "Next {0}", "موج بعد {0}" },
            new[] { "battle.early_bonus", "Early call: +{0} coins", "فراخوان زودهنگام: {0}+ سکه" },
            new[] { "battle.not_enough_coins", "Not enough coins", "سکهٔ کافی نداری" },
            new[] { "battle.not_ready", "Not ready yet", "هنوز آماده نیست" },
            new[] { "battle.no_item", "None left", "دیگر نداری" },
            new[] { "battle.buy_item", "You have no {0}. Buy one for {1} gems?", "{0} نداری. یکی با {1} گوهر می‌خری؟" },
            new[] { "battle.choose_path", "Choose one of two paths. Tap again to confirm.", "یکی از دو راه را برگزین. برای تأیید دوباره لمس کن." },
            new[] { "battle.sell", "Sell", "فروش" },
            new[] { "battle.sell_body", "Sell this tower for {0} coins.", "این برج را به {0} سکه بفروش." },
            new[] { "battle.paused", "Paused", "درنگ" },
            new[] { "battle.resume", "Resume", "ادامه" },
            new[] { "battle.restart", "Restart", "از نو" },
            new[] { "battle.sound_off", "Sound off", "خاموش کردن صدا" },
            new[] { "battle.sound_on", "Sound on", "روشن کردن صدا" },
            new[] { "battle.quit", "Leave battle", "ترک نبرد" },
            new[] { "battle.victory", "Victory!", "پیروزی!" },
            new[] { "battle.defeat", "Defeat", "شکست" },
            new[] { "battle.defeat_body", "The enemy broke through. But a hero never gives up!", "دشمن راه را شکافت. اما پهلوان هرگز دست نمی‌کشد!" },
            new[] { "battle.double_gold", "Double gold", "زر دوبرابر" },
            new[] { "battle.replay", "Replay", "دوباره" },
            new[] { "battle.continue", "Continue", "ادامه" },
            new[] { "battle.retry", "Try again", "دوباره" },
            new[] { "battle.to_map", "Map", "نقشه" },
            new[] { "battle.revive_ad", "Watch an ad: +{0} lives", "تماشای آگهی: {0}+ جان" },
            new[] { "battle.revive_gems", "+{0} lives for {1} gems", "{0}+ جان با {1} گوهر" },
            new[] { "battle.hero_joined", "{0} has joined you!", "{0} به یاری‌ات آمد!" },
            new[] { "battle.target.hero", "Tap where the hero should go", "جایی را که پهلوان باید برود لمس کن" },
            new[] { "battle.target.arrows", "Tap where Arash's arrows should fall", "جای فرود تیرهای آرش را لمس کن" },
            new[] { "battle.target.reinforce", "Tap where Kaveh's smiths should fight", "جای نبرد آهنگران کاوه را لمس کن" },
            new[] { "battle.target.naphtha", "Tap where to throw the naphtha", "جای پرتاب کوزهٔ نفت را لمس کن" },
            new[] { "battle.target.rally", "Tap the soldiers' new post", "جای تازهٔ سربازان را لمس کن" },
            new[] { "hint.build", "Tap a plot beside the road to build a tower", "برای ساختن برج، یکی از زمین‌های کنار راه را لمس کن" },
            new[] { "hint.horn", "Blow the war horn to call the first wave", "برای آغاز نخستین موج، شیپور جنگ را بزن" },
            new[] { "hint.hero", "Tap your hero, then the map, to send them there", "پهلوانت را لمس کن، سپس جایی از نقشه را" },
        };
    }
}
