namespace IranVsTuran.Localization
{
    /// <summary>
    /// String tables: { key, English, Persian }. Split by topic; <see cref="All"/> lists them for <see cref="Loc"/>.
    /// </summary>
    public static partial class Strings
    {
        public static readonly string[][][] All = { UI, Content, Story };

        /// <summary>Names and lore of chapters, levels, enemies, towers, heroes, items and upgrades.</summary>
        static readonly string[][] Content =
        {
            // ---- chapters ----
            new[] { "chapter.invasion", "Afrasiab's Invasion", "یورش افراسیاب" },
            new[] { "chapter.haftkhan", "The Seven Labours", "هفت‌خوان رستم" },
            new[] { "chapter.sohrab", "Rostam and Sohrab", "رستم و سهراب" },
            new[] { "chapter.siavash", "Vengeance for Siavash", "کین سیاوش" },
            new[] { "chapter.damavand", "Bonus: Damavand", "ویژه: دماوند" },

            // ---- levels ----
            new[] { "level.l1", "Crossing of the Jeyhun", "گذرگاه جیحون" },
            new[] { "level.l1.desc", "Turanian raiders are crossing the river. Stop them at the ford.", "تاراجگران تورانی از رود می‌گذرند. جلوی آن‌ها را در گذرگاه بگیر." },
            new[] { "level.l2", "The Border Fort", "دژ مرزی" },
            new[] { "level.l2.desc", "The enemy attacks from two sides. Guard both roads.", "دشمن از دو سو می‌تازد. هر دو راه را نگه دار." },
            new[] { "level.l3", "Plain of Garsivaz", "دشت گرسیوز" },
            new[] { "level.l3.desc", "Afrasiab's brother Garsivaz leads the assault himself.", "گرسیوز، برادر افراسیاب، خودش یورش را رهبری می‌کند." },
            new[] { "level.l4", "The Lion's Thicket", "بیشهٔ شیر" },
            new[] { "level.l4.desc", "The first labours: a fierce lion, beasts and the first divs of Mazandaran.", "نخستین خوان‌ها: شیر ژیان، جانوران و نخستین دیوان مازندران." },
            new[] { "level.l5", "Lair of the Dragon", "کنام اژدها" },
            new[] { "level.l5.desc", "In the third labour a dragon blocks the road.", "در خوان سوم، اژدهایی راه را بسته است." },
            new[] { "level.l6", "Cave of the White Div", "غار دیو سپید" },
            new[] { "level.l6.desc", "The seventh labour. Defeat the White Div and free the king.", "خوان هفتم. دیو سپید را شکست بده و شاه را آزاد کن." },
            new[] { "level.l7", "The White Castle", "دژ سپید" },
            new[] { "level.l7.desc", "Gordafarid defends the White Castle against Sohrab's army. Win, and she joins you.", "گردآفرید از دژ سپید در برابر سپاه سهراب دفاع می‌کند. پیروز شو تا به یاری‌ات بیاید." },
            new[] { "level.l8", "The Turanian Camp", "اردوگاه توران" },
            new[] { "level.l8.desc", "Turan's army pours out of its camp on two roads.", "سپاه توران از دو راه از اردوگاهش بیرون می‌ریزد." },
            new[] { "level.l9", "Houman's Charge", "یورش هومان" },
            new[] { "level.l9.desc", "Houman, Turan's fiercest general, charges with his cavalry.", "هومان، تندخوترین سردار توران، با سوارانش می‌تازد." },
            new[] { "level.l10", "Mount Hamavan", "کوه هماون" },
            new[] { "level.l10.desc", "Ashkbus the archer, and the war elephants of the Khaqan of Chin.", "اشکبوس کماندار و پیلان جنگی خاقان چین." },
            new[] { "level.l11", "The Wind Div", "دیو باد" },
            new[] { "level.l11.desc", "Akvan Div moves like the wind. Watch where he lands.", "اکوان دیو چون باد جابه‌جا می‌شود. حواست باشد کجا فرود می‌آید." },
            new[] { "level.l12", "Gang-Dezh", "گنگ‌دژ" },
            new[] { "level.l12.desc", "Afrasiab's fortress. Three roads, one final battle.", "دژ افراسیاب. سه راه، یک نبرد واپسین." },
            new[] { "level.l13", "Damavand", "دماوند" },
            new[] { "level.l13.desc", "Bonus battle: Zahhak the serpent-shouldered breaks his chains.", "نبرد ویژه: ضحاک ماردوش زنجیرهایش را می‌گسلد." },

            // ---- enemies ----
            new[] { "enemy.soldier", "Turanian Soldier", "سرباز تورانی" },
            new[] { "lore.soldier", "The backbone of Afrasiab's army: sword, shield and a long march.", "ستون سپاه افراسیاب؛ با شمشیر و سپر و راهی دراز." },
            new[] { "enemy.raider", "Turanian Raider", "تاراجگر تورانی" },
            new[] { "lore.raider", "Light horsemen who burn villages and vanish before dawn. Fast.", "سواران سبک‌باری که دهکده‌ها را می‌سوزانند و پیش از سپیده ناپدید می‌شوند. تندرو." },
            new[] { "enemy.archer", "Turanian Archer", "کماندار تورانی" },
            new[] { "lore.archer", "Shoots at your soldiers from a distance.", "از دور سربازانت را به تیر می‌بندد." },
            new[] { "enemy.heavy", "Armoured Turanian", "جوشن‌پوش تورانی" },
            new[] { "lore.heavy", "Heavy mail turns arrows and stones aside. Use fire temples.", "جوشن سنگین تیر و سنگ را پس می‌زند. از آتشکده‌ها بهره بگیر." },
            new[] { "enemy.cavalry", "Turanian Cavalry", "سوار تورانی" },
            new[] { "lore.cavalry", "Armoured riders who break through lines quickly.", "سواران زره‌پوشی که به‌تندی صف‌ها را می‌شکافند." },
            new[] { "enemy.shaman", "Turanian Sorcerer", "جادوگر تورانی" },
            new[] { "lore.shaman", "Heals wounded comrades. Resists magic. Kill him first.", "زخمیان را درمان می‌کند و در برابر جادو پایدار است. اول او را از پا درآور." },
            new[] { "enemy.elephant", "War Elephant", "پیل جنگی" },
            new[] { "lore.elephant", "The Khaqan of Chin brought elephants to Turan's war. Costs three lives if it gets through.", "خاقان چین پیلان جنگی به یاری توران آورد. اگر بگذرد سه جان می‌گیرد." },
            new[] { "enemy.lion", "Fierce Lion", "شیر ژیان" },
            new[] { "lore.lion", "In the first labour a lion attacked Rostam in his sleep, and Rakhsh killed it.", "در خوان نخست، شیری به رستمِ خفته تاخت و رخش او را کشت." },
            new[] { "enemy.gorgsar", "Wolf-head", "گرگسار" },
            new[] { "lore.gorgsar", "Half man, half wolf: the dreaded Gorgsaran of the Shahnameh.", "نیمی آدم و نیمی گرگ: گرگسارانِ هراس‌انگیز شاهنامه." },
            new[] { "enemy.imp", "Lesser Div", "دیوچه" },
            new[] { "lore.imp", "Small, fast and many. They burst out when a div dies.", "کوچک، تند و فراوان. با مرگ هر دیو بیرون می‌ریزند." },
            new[] { "enemy.div", "Div", "دیو" },
            new[] { "lore.div", "The demons of Mazandaran: huge, strong and hard to stop. Costs two lives.", "دیوان مازندران: تنومند، زورمند و سخت‌شکن. دو جان می‌گیرد." },
            new[] { "enemy.winged", "Winged Div", "دیو بالدار" },
            new[] { "lore.winged", "Flies over your soldiers. Only archers, fire temples and heroes can reach it.", "از فراز سربازانت پرواز می‌کند. تنها کمانداران، آتشکده‌ها و پهلوانان به آن می‌رسند." },
            new[] { "enemy.witch", "Witch", "زن جادو" },
            new[] { "lore.witch", "In the fourth labour a witch appeared as a beautiful woman. She heals the divs.", "در خوان چهارم، جادوگری به شکل زنی زیبا پدیدار شد. او دیوان را درمان می‌کند." },
            new[] { "enemy.snake", "Serpent of Zahhak", "مار ضحاک" },
            new[] { "lore.snake", "Born from the shoulders of the tyrant.", "زاده از دوش ستمگر." },
            new[] { "enemy.garsivaz", "Garsivaz", "گرسیوز" },
            new[] { "lore.garsivaz", "Afrasiab's brother, whose lies would one day cost Siavash his life. Calls soldiers to his side.", "برادر افراسیاب که روزی دروغ‌هایش جان سیاوش را گرفت. سربازان را به یاری فرا می‌خواند." },
            new[] { "enemy.dragon", "Dragon", "اژدها" },
            new[] { "lore.dragon", "In the third labour Rostam and Rakhsh fought a dragon in the dark. Breathes fire on soldiers.", "در خوان سوم، رستم و رخش در تاریکی با اژدهایی جنگیدند. بر سربازان آتش می‌دمد." },
            new[] { "enemy.divsepid", "The White Div", "دیو سپید" },
            new[] { "lore.divsepid", "Lord of the divs of Mazandaran. Stomps the ground and hurls rocks at towers.", "سالار دیوان مازندران. زمین را می‌کوبد و به برج‌ها سنگ پرتاب می‌کند." },
            new[] { "enemy.houman", "Houman", "هومان" },
            new[] { "lore.houman", "Turan's fiercest general. Grows furious when wounded and calls his riders.", "تندخوترین سردار توران. زخمی که شود خشمگین‌تر می‌شود و سوارانش را فرا می‌خواند." },
            new[] { "enemy.ashkbus", "Ashkbus", "اشکبوس" },
            new[] { "lore.ashkbus", "A champion who mocked the Iranians at Mount Hamavan, until Rostam's single arrow.", "پهلوانی که در کوه هماون ایرانیان را به ریشخند گرفت، تا تیرِ یگانهٔ رستم." },
            new[] { "enemy.akvan", "Akvan Div", "اکوان دیو" },
            new[] { "lore.akvan", "A div who moves like the wind. He once threw the sleeping Rostam into the sea.", "دیوی که چون باد می‌رود. روزی رستمِ خفته را به دریا انداخت." },
            new[] { "enemy.afrasiab", "Afrasiab", "افراسیاب" },
            new[] { "lore.afrasiab", "King of Turan and Iran's greatest enemy. Silences towers and summons his guard.", "شاه توران و بزرگ‌ترین دشمن ایران. برج‌ها را از کار می‌اندازد و نگهبانانش را فرا می‌خواند." },
            new[] { "enemy.zahhak", "Zahhak", "ضحاک" },
            new[] { "lore.zahhak", "The serpent-shouldered tyrant whom Fereydun chained inside Damavand.", "ستمگر ماردوشی که فریدون او را در دل دماوند به بند کشید." },

            // ---- towers ----
            new[] { "family.archer", "Fast arrows. Hits flying enemies too.", "تیرهای پیاپی. به دشمنان پرنده هم می‌رسد." },
            new[] { "family.barracks", "Soldiers who block the road and fight.", "سربازانی که راه را می‌بندند و می‌جنگند." },
            new[] { "family.mage", "Sacred fire that ignores armour.", "آتش سپند که از زره می‌گذرد." },
            new[] { "family.artillery", "Stones that hit whole groups. Cannot hit flyers.", "سنگ‌هایی که به گروه دشمنان آسیب می‌زنند. به پرندگان نمی‌رسد." },
            new[] { "tower.archer1", "Archer Post", "دیدگاه کمانداران" },
            new[] { "tower.archer2", "Archer Tower", "برج کمانداران" },
            new[] { "tower.archer3", "Marksmen Tower", "برج تیراندازان" },
            new[] { "tower.archer4a", "Tower of Arash", "برج آرش" },
            new[] { "tower.archer4a.desc", "Long range. Mighty shots that sometimes deal triple damage.", "بُرد بلند. تیرهای سهمگینی که گاه سه برابر آسیب می‌زنند." },
            new[] { "tower.archer4b", "Kayanian Volley", "تیرباران کیانی" },
            new[] { "tower.archer4b.desc", "Very fast. Shoots two enemies at once.", "بسیار تند. هم‌زمان به دو دشمن تیر می‌زند." },
            new[] { "tower.barracks1", "Guard Post", "پاسگاه" },
            new[] { "tower.barracks2", "Barracks", "سربازخانه" },
            new[] { "tower.barracks3", "Heroes' Hall", "سرای پهلوانان" },
            new[] { "tower.barracks4a", "Zabuli Champions", "پهلوانان زابلی" },
            new[] { "tower.barracks4a.desc", "Three tough champions whose wounds heal over time.", "سه پهلوان سرسخت که زخم‌هایشان کم‌کم درمان می‌شود." },
            new[] { "tower.barracks4b", "Kaviani Legion", "سپاه کاویانی" },
            new[] { "tower.barracks4b.desc", "Four soldiers under Kaveh's banner.", "چهار سرباز زیر درفش کاویانی." },
            new[] { "tower.mage1", "Fire Altar", "آتشدان" },
            new[] { "tower.mage2", "Fire House", "آتشگاه" },
            new[] { "tower.mage3", "Fire Temple", "آتشکده" },
            new[] { "tower.mage4a", "Adur Gushnasp", "آذرگشسب" },
            new[] { "tower.mage4a.desc", "The great sacred fire: heavy damage that keeps burning.", "آتش بزرگ و سپند: آسیب سنگین و سوزش پیوسته." },
            new[] { "tower.mage4b", "Light of Sorush", "فروغ سروش" },
            new[] { "tower.mage4b.desc", "Holy light that slows enemies and leaps between them.", "پرتو سپند که دشمنان را کند می‌کند و میانشان می‌جهد." },
            new[] { "tower.artillery1", "Slingers", "فلاخن‌اندازان" },
            new[] { "tower.artillery2", "Catapult", "منجنیق" },
            new[] { "tower.artillery3", "Great Catapult", "منجنیق بزرگ" },
            new[] { "tower.artillery4a", "Mountain Hurler", "کوه‌افکن" },
            new[] { "tower.artillery4a.desc", "Huge boulders that stun enemies.", "تخته‌سنگ‌های غول‌آسایی که دشمن را گیج می‌کنند." },
            new[] { "tower.artillery4b", "Naphtha Thrower", "نفت‌انداز" },
            new[] { "tower.artillery4b.desc", "Jars of naphtha that set the ground on fire.", "کوزه‌های نفت که زمین را شعله‌ور می‌کنند." },

            // ---- heroes ----
            new[] { "hero.rostam", "Rostam", "رستم" },
            new[] { "hero.rostam.desc", "The world champion, son of Zal. Strong and tough.", "جهان‌پهلوان، پسر زال. زورمند و سرسخت." },
            new[] { "hero.rostam.ability", "Heavy Mace: stuns and damages every enemy around him.", "گرز گران: دشمنان پیرامونش را گیج می‌کند و آسیب می‌زند." },
            new[] { "hero.gordafarid", "Gordafarid", "گردآفرید" },
            new[] { "hero.gordafarid.desc", "The warrior maiden of the White Castle. Shoots from afar.", "بانوی جنگاور دژ سپید. از دور تیر می‌اندازد." },
            new[] { "hero.gordafarid.ability", "Volley: arrows rain on every enemy in range.", "تیرباران: بر همهٔ دشمنانِ در تیررس تیر می‌بارد." },
            new[] { "hero.zal", "Zal", "زال" },
            new[] { "hero.zal.desc", "The white-haired sage raised by the Simorgh. Fights with magic.", "پیر سپیدموی پرورده‌ی سیمرغ. با جادو می‌جنگد." },
            new[] { "hero.zal.ability", "Simorgh's Feather: heals allies and burns nearby enemies.", "پر سیمرغ: یاران را درمان می‌کند و دشمنان پیرامون را می‌سوزاند." },
            new[] { "hero.esfandiar", "Esfandiar", "اسفندیار" },
            new[] { "hero.esfandiar.desc", "The brazen-bodied prince. Almost impossible to wound.", "شاهزادهٔ رویین‌تن. زخم برنمی‌دارد." },
            new[] { "hero.esfandiar.ability", "Brazen Body: invulnerable for a few seconds, striking all around.", "رویین‌تنی: چند ثانیه آسیب‌ناپذیر می‌شود و پیرامونش را درهم می‌کوبد." },
            new[] { "skin.rostam_babr", "Babr-e Bayan", "ببر بیان" },
            new[] { "skin.rostam_royal", "Royal Blue", "جامهٔ شاهوار" },
            new[] { "skin.gordafarid_white", "White Castle", "دژ سپید" },
            new[] { "skin.esfandiar_gold", "Golden Prince", "شاهزادهٔ زرین" },
            new[] { "character.kavus", "Kay Kavus", "کاووس‌شاه" },
            new[] { "character.kaykhosrow", "Kay Khosrow", "کیخسرو" },
            new[] { "character.sohrab", "Sohrab", "سهراب" },

            // ---- items, spells, upgrades ----
            new[] { "item.nushdaru", "Nushdaru", "نوشدارو" },
            new[] { "item.nushdaru.desc", "The healing elixir: +5 lives.", "داروی درمان: ۵ جان می‌افزاید." },
            new[] { "item.simorgh", "Simorgh Feather", "پر سیمرغ" },
            new[] { "item.simorgh.desc", "Freezes every enemy for 5 seconds.", "همهٔ دشمنان را ۵ ثانیه از جنبش بازمی‌دارد." },
            new[] { "item.naphtha", "Naphtha Jar", "کوزهٔ نفت" },
            new[] { "item.naphtha.desc", "A great blaze wherever you throw it.", "هر جا بیندازی آتشی سهمگین برپا می‌کند." },
            new[] { "item.treasure", "Kay Khosrow's Treasure", "گنج کیخسرو" },
            new[] { "item.treasure.desc", "+250 coins in battle.", "۲۵۰ سکه در نبرد." },
            new[] { "spell.arrows", "Arash's Rain", "باران تیر آرش" },
            new[] { "spell.reinforce", "Kaveh's Smiths", "یاری کاوه" },
            new[] { "upgrade.archer_dmg", "Arash's Arrows", "تیرهای آرش" },
            new[] { "upgrade.archer_dmg.desc", "Archer damage +10% per rank.", "آسیب کمانداران در هر رتبه ۱۰٪ بیشتر." },
            new[] { "upgrade.archer_range", "Eagle Eye", "چشم عقاب" },
            new[] { "upgrade.archer_range.desc", "Archer range +6% per rank.", "بُرد کمانداران در هر رتبه ۶٪ بیشتر." },
            new[] { "upgrade.barracks_hp", "Woven Mail", "زره‌بافت" },
            new[] { "upgrade.barracks_hp.desc", "Soldier health +12% per rank.", "جان سربازان در هر رتبه ۱۲٪ بیشتر." },
            new[] { "upgrade.barracks_respawn", "Fresh Recruits", "سربازگیری" },
            new[] { "upgrade.barracks_respawn.desc", "Fallen soldiers return 12% sooner per rank.", "سربازان در هر رتبه ۱۲٪ زودتر بازمی‌گردند." },
            new[] { "upgrade.mage_dmg", "Sacred Flame", "شعلهٔ سپند" },
            new[] { "upgrade.mage_dmg.desc", "Fire temple damage +10% per rank.", "آسیب آتشکده‌ها در هر رتبه ۱۰٪ بیشتر." },
            new[] { "upgrade.mage_speed", "Chant of the Mobads", "سرود موبدان" },
            new[] { "upgrade.mage_speed.desc", "Fire temples attack 6% faster per rank.", "آتشکده‌ها در هر رتبه ۶٪ تندتر می‌زنند." },
            new[] { "upgrade.artillery_dmg", "Heavier Stones", "سنگ‌های سنگین‌تر" },
            new[] { "upgrade.artillery_dmg.desc", "Siege damage +10% per rank.", "آسیب منجنیق‌ها در هر رتبه ۱۰٪ بیشتر." },
            new[] { "upgrade.artillery_splash", "Wide Impact", "ضربهٔ گسترده" },
            new[] { "upgrade.artillery_splash.desc", "Siege blast radius +8% per rank.", "گسترهٔ ضربهٔ منجنیق‌ها در هر رتبه ۸٪ بیشتر." },
            new[] { "upgrade.spell_arrows", "Rain of Arrows", "باران تیر" },
            new[] { "upgrade.spell_arrows.desc", "Arash's Rain hits 20% harder per rank.", "باران تیر آرش در هر رتبه ۲۰٪ سخت‌تر می‌زند." },
            new[] { "upgrade.spell_reinforce", "Kaveh's Smiths", "آهنگران کاوه" },
            new[] { "upgrade.spell_reinforce.desc", "Reinforcements 20% stronger per rank.", "نیروی کمکی در هر رتبه ۲۰٪ نیرومندتر." },
            new[] { "upgrade.economy", "Royal Treasury", "خزانهٔ شاهی" },
            new[] { "upgrade.economy.desc", "+20 starting coins per rank.", "در هر رتبه ۲۰ سکهٔ آغازین بیشتر." },

            // ---- products ----
            new[] { "product.gems_small", "Pouch of Gems", "کیسهٔ گوهر" },
            new[] { "product.gems_medium", "Chest of Gems", "صندوقچهٔ گوهر" },
            new[] { "product.gems_large", "Coffer of Gems", "گنجینهٔ گوهر" },
            new[] { "product.gems_huge", "Royal Treasury", "گنج شاهی" },
            new[] { "product.starter_pack", "Hero's Pack", "بستهٔ پهلوان" },
            new[] { "product.battle_pass", "Royal Battle Pass", "نبردنامهٔ شاهی" },
        };
    }
}
